[workspace]
members = ["client", "server"]
resolver = "2"

[workspace.dependencies]
tonic = "0.10"
prost = "0.12"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tonic-build = "0.10"
